module.exports = {
    TS_SUCCESS: 1,
    TS_FAILED: 0,
    TS_SUCCESS_CODE: 200,
    TS_SERVER_ERROR_CODE: 500,
    TS_NOT_FOUND_CODE: 404,
    TS_BAD_REQUEST_CODE: 400,
    TS_RESOURCE_CREATED_CODE: 201,
    TS_UNAUTHORIZED_CODE: 401,
    TS_PROCESSING_CODE: 202,
    TS_CONFLICTS_CODE: 409,
    TS_TOO_MANY_REQUEST_CODE: 429,
    TS_PAYMENT_REQUIRED_CODE: 402
}